development: &developement
  adapter: postgresql
  encoding: unicode
  database: airportus_developement
  pool: 5
  host: localhost
  port: 5432
  username: ivan
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: airportus_production
  pool: 5
  host: localhost
  port: 5432
  username: ivan
  password:

test:
  <<: *developement
  database: airportus_test
  host: localhost
  port: 5432
